### PR TITLE
NCS-67 Add statement of capital page navigation

### PR DESCRIPTION
**Pull request by markpit**
Sorry for the large number of files changed. Most of them are just changing the usage of the utils/url.ts module.

the main changes are statement.of.capital.controller, the unit test for it and the template for it.

I've changed the utils/url.ts to wrap the function in an object. This was to allow me to mock the function only for certain tests as opposed to having it mocked for all the tests in a test module. By wrapping in an object, we can now use jest.spyOn (requires an object). This means that we can mock that function using spyOn in a particular test and then restore the mock back to its non-mocked form ready for the other tests to use it as normal.  The mockRestore() only works on mocks created with spyOn().

### CODE REVIEW

**Comment by AlfredBwomezi** [comment]
Might be worth implementing the changes to utils.url.ts to confirm.sic.code.controller.ts and tests  as well.

**Comment by ICoxCH** [comment]
> Might be worth implementing the changes to utils.url.ts to confirm.sic.code.controller.ts and tests as well.

Hi Alfred, i'm taking over this PR as Mark is on holiday. But it appears that sic code controller has been changed to use the new url utils class already?

**Comment by AlfredBwomezi** [comment]
The utils.url has been changed into an object but the has not been updated int confirm.sic.code.controller as has been in [confirm.company.controller.ts, for example](https://github.com/companieshouse/confirmation-statement-web/pull/158/files#diff-1e9d2eecdab5cb51b8ceee8a301a995da43d27280d01b53a69e9b93116d8a01b).

**Comment by ICoxCH** [comment]
> The utils.url has been changed into an object but the has not been updated int confirm.sic.code.controller as has been in [confirm.company.controller.ts, for example](https://github.com/companieshouse/confirmation-statement-web/pull/158/files#diff-1e9d2eecdab5cb51b8ceee8a301a995da43d27280d01b53a69e9b93116d8a01b).

Is this not it [updated?](https://github.com/companieshouse/confirmation-statement-web/pull/158/files#diff-85ca6106f86f2c4a1added8084d9ef6bb19623b5abd2247edd7ba9d89d041374R13)

**Comment by AlfredBwomezi** [comment]
My GitHub was out of sync and i couldn't see all. All looks good. :)

**Review by AlfredBwomezi — APPROVED** [review]

**Pull request merged**
